version: "3"
services:
  geth-bootnode:
    hostname: geth-bootnode
    environment: 
      - nodekeyhex=08f0e1dee5c1b4645f3331a566009e41a4514b6cd28656d63d0449ecf812812b #Needs to be fix, so that the miners know the resulting enode id
    build:
      context: .
      dockerfile: Bootnode.Dockerfile
    container_name: geth-bootnode-1
    ports: 
      - 30301:30301/udp
    networks:
      chainnet: 
        ipv4_address: 172.25.0.101 # The miners need to know the IP address later on

  geth-miner-1:
    hostname: geth-miner-1
    depends_on: 
      - geth-bootnode
    environment:
      - address=0x8cc5a1a0802db41db826c2fcb72423744338dcb0 #derived from the private key which is passed in the args
      - bootnodeId=76a8171707eca17647a47ca99ffd348927dfa60102792ea349a25d5192e61855be83b786e376276a306afcceea4ffd1c9c77e4370b417efc39f328a0d068004c #derived from the nodekeyhex of the bootnode
      - bootnodeIp=172.25.0.101  
    build: 
      context: .
      dockerfile: Node.Dockerfile
      args:
        privatekey: df504d175ae63abf209bad9dda965310d99559620550e74521a6798a41215f46 # Please don't do something like this in production, okay?
        password: pass
    container_name: geth-miner-1
    ports:
      - 8545:8545
    volumes:
      - eth-data-1:/root/.ethereum # Allows blockchain to persist between container boots
    networks:
      chainnet:
        ipv4_address: 172.25.0.102 # The monitor needs to know this address

  geth-miner-2:
    hostname: geth-miner-2
    depends_on: 
      - geth-bootnode
    environment:
      - address=0x3590aca93338b0721966a8d0c96ebf2c4c87c544 #derived from the private key which is passed in the args
      - bootnodeId=76a8171707eca17647a47ca99ffd348927dfa60102792ea349a25d5192e61855be83b786e376276a306afcceea4ffd1c9c77e4370b417efc39f328a0d068004c #derived from the nodekeyhex of the bootnode
      - bootnodeIp=172.25.0.101
    build: 
      context: .
      dockerfile: Node.Dockerfile
      args:
        privatekey: bc5b578e0dcb2dbf98dd6e5fe62cb5a28b84a55e15fc112d4ca88e1f62bd7c35
        password: word
    container_name: geth-miner-2
    ports:
      - 8546:8545
    volumes:
     - eth-data-2:/root/.ethereum # Allows blockchain to persist between container boots
    networks:
      chainnet:
        ipv4_address: 172.25.0.104

  monitoring:
   hostname: monitoring
   depends_on: 
     - geth-miner-1
   build:
     context: ./Monitoring
     dockerfile: Monitoring.Dockerfile
   container_name: monitoring
   ports:
    - 3000:3000
   networks:
    chainnet:
      ipv4_address: 172.25.0.103

  geth-explorer:
    hostname: geth-explorer
    depends_on:
      - geth-miner-1
    ports:
      - 8080:8080
    build:
      context: ./Monitoring
      dockerfile: Explorer.Dockerfile
    container_name: geth-explorer
    networks:
      chainnet:
        ipv4_address: 172.25.0.125

networks:
  chainnet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24

volumes:
  eth-data-1:
  eth-data-2: