version: "3"
services:
  content-backend:
    hostname: content-backend
    environment:
      - MONGO_ADDRESS=mongodb://host.docker.internal:27017/ticketing  # Change this to suit your mongo db endpoint
      - BLOCKCHAIN_ADDR=http://host.docker.internal:8545 # Change this to suit your blockchain endpoint
      - PRIVATE_KEY_1=bc5b578e0dcb2dbf98dd6e5fe62cb5a28b84a55e15fc112d4ca88e1f62bd7c35
      - JWT_KEY=some_form_of_secret
    build:
      context: .
    container_name: content-backend
    ports:
      - 5000:5000